CREATE TABLE User_Account (
	id INT UNSIGNED NOT NULL auto_increment,
	Email VARCHAR(130) NOT NULL,
	Fname VARCHAR(70) NOT NULL,
	Lname VARCHAR(70) NOT NULL,
  Phone BIGINT UNSIGNED NOT NULL,
	StreetAddress VARCHAR(70) NOT NULL,
	City VARCHAR(50) NOT NULL,
	State VARCHAR(50) NOT NULL,
	ZipCode MEDIUMINT UNSIGNED,
	Salt CHAR(10) NOT NULL,
	Hash CHAR(40) NOT NULL,
	PRIMARY KEY(id),
	UNIQUE KEY(email)
);

CREATE TABLE Profile (
	id INT UNSIGNED NOT NULL auto_increment,
	Name VARCHAR(30) NOT NULL,
	AcctID INT UNSIGNED NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY (AcctID) REFERENCES User_Account(id),
	UNIQUE(AcctID, Name)
);

CREATE TABLE Movie (
	id INT UNSIGNED NOT NULL auto_increment,
	Name VARCHAR(100) NOT NULL,
	YearReleased SMALLINT UNSIGNED NOT NULL,
	Runtime SMALLINT UNSIGNED,
	Description VARCHAR(255),
	PRIMARY KEY(id),
	UNIQUE KEY(Name, YearReleased)
);

CREATE TABLE Views_Movie (
	MovieID INT UNSIGNED NOT NULL,
	ProfileID INT UNSIGNED NOT NULL,
	PercentComplete TINYINT UNSIGNED NOT NULL,  	
  PRIMARY KEY(MovieID, ProfileID),
  FOREIGN KEY (MovieID) REFERENCES Movie(id),
	FOREIGN KEY (ProfileID) REFERENCES Profile(id)
);
